# Generated by Django 3.1.7 on 2021-04-14 15:45

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chat_room',
            field=django_bleach.models.BleachField(default=datetime.datetime(2021, 4, 14, 15, 45, 50, 829226, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=django_bleach.models.BleachField(max_length=50),
        ),
    ]
